version: '4.0'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Teste@Teste123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - compose-bridge
    volumes:
      - sqlserverdb:/var/opt/mssql
  
  apiprodutos:
    build:
      context: .repos/apiprodutos
      dockerfile: dockerfile
    container_name: produtosapi
    networks:
      - compose-bridge
    ports: 
      - 8680:8080
    depends_on:
      - sqlserver
  
  apiestoque:
    build: 
      context: .  
      dockerfile: dockerfile
    image: apiestoque:1.0
    container_name: apiestoque
    networks:
      - compose-bridge
    ports: 
      - 8681:8080
    depends_on:
      - sqlserver
      
networks:
  compose-bridge:
    driver: bridge

volumes:
  sqlserverdb: